### ISSUE TITLE
"Cannot Get / Error: not found" after start

### ISSUE THREAD

**Issue by Morethanevil** [Phalcode/gamevault-backend#137]
**Describe the bug**
After a fresh install I get this error if I start the docker stack:

```
{
  "message": "Cannot GET /",
  "error": "Not Found",
  "statusCode": 404
}
```

**To Reproduce**

I only made a few modifications on the docker-compose.yml

```
version: "3.8"
services:
  gamevault-backend:
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    container_name: gamevault
    environment:
      DB_HOST: db
      DB_DATABASE: gamevault
      DB_USERNAME: gamevaultuser
      DB_PASSWORD: supersecret
      # The Following Line grants Admin Role to account with this username upon registration.
      SERVER_ADMIN_USERNAME: mtex
      # Uncomment and Insert your RAWG API Key here if you have one (http://rawg.io/login?forward=developer)
      # RAWG_API_KEY: YOURAPIKEYHERE
    volumes:
      # Mount the folder where your games are
      - /docker/gamevault/files:/files
      # Mount the folder where gamevault should store its images
      - /docker/gamevault/images:/images
    ports:
      - 8400:8080
  db:
    image: postgres:15-alpine
    container_name: gamevaultdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevaultuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: gamevault
    volumes:
      # Mount the folder where your postgres database files should land
      - /docker/gamevault/db:/var/lib/postgresql
```

**Expected behavior**

Open the normal web ui

**Screenshots**
See here:
![Screenshot 2023-07-21 202304](https://github.com/Phalcode/gamevault-backend/assets/110860055/9999259d-76b8-499d-b6e0-873b7157005d)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Browser Vivaldi & Firefox
 - Version latest
