### ISSUE TITLE
Implement metadata yaml

### ISSUE THREAD

**Issue by wargio** [Phalcode/gamevault-backend#223]
**Is your feature request related to a problem? Please describe.**
The backend should switch to a metadata written in a YAML file instead of the folder title.
This would allow also to specify where the installer is and what is called, besides also allowing patching multiple files if the game has multiple patches.

The current folder structure works for movies, music albums and tv series but is not suitable for software (including games).

Many old games has patches as self-extractor execs and the GameVault could also support zip for in-folder patching.

I strongly suggest to have something like this:

Old naming: `The Wandering Village (v0.1.32) (EA) (2022).iso`

New naming: `The Wandering Village (2022)/metadata.yaml`

```yaml
versions:
  0.1.32:
    path: TheWanderingVillage.v0.1.32.zip
    early-access: false
    no-cache: false
    game-type: portable
    patches:
      - TheWanderingVillage.v0.2.01.zip
      - TheWanderingVillage.v0.2.02.zip
    installer:
  0.2.00:
    path: TheWanderingVillage.v0.2.00.iso
    early-access: false
    no-cache: false
    game-type: setup
    patches:
      - TheWanderingVillage.v0.2.01.exe
      - TheWanderingVillage.v0.2.02.exe
      - TheWanderingVillage.v0.2.03.exe
    installer: setup.exe
```

This also will allow in the future to add extra feature by easily adding metadata.
