### ISSUE TITLE
ARM64 - docker container crashes

### ISSUE THREAD

**Issue by LoganJFisher** [Phalcode/gamevault-backend#272]
**Describe the bug**
Docker container crashes

**To Reproduce**
1. Download the phalcode/gamevault-backend image
2. Create a container for that image (the only changes I made were to make it auto-restart and to set a local port number)
3. Run container
4. Container crashes a few seconds later 

**Expected behavior**
I expect the container to run successfully.

**Screenshots**
![tco14p0](https://github.com/Phalcode/gamevault-backend/assets/63993409/7459201d-ff29-457a-888b-8822e45eda76)

**Desktop (please complete the following information):**
 - Device: Synology DS423 - [Realtek RTD1619B - ARM V8.2 Cortex-A55 64-bit]
 - OS: Synology Diskstation Manager (DSM)
 - Version: DSM 7.2.1-69057 Update 3

**Comment by Alfagun74** [comment]
Hi @LoganJFisher, it looks like your Container can not connect to your postgres server. Could you share your compose-file with me?

**Comment by Alfagun74** [comment]
Also see:
https://gamevau.lt/docs/server-docs/setup/docker-compose#step-1-creating-a-docker-compose-file

Or, if you don't want to use postgres:
https://gamevau.lt/docs/server-docs/setup/docker-compose#alternative-step-1-running-without-a-postgresql-database

**Comment by LoganJFisher** [comment]
Would it be possible for you to add setup instructions for Synology Container Manager? It uses a GUI instead of being command line, so I'm not entirely sure how to use the instructions you have provided there.

I don't have Postgres set up (and have struggled to figure it out), but I'm not strictly opposed to using it.

**Comment by Alfagun74** [comment]
@LoganJFisher I understand your perspective and thanks for using GameVault in advance. 

I haven't delved into the Synology Container Manager extensively, so initially, I didn't find an apparent way to easily publish a one-click app template or anything similar for it. However, it seems like it's essentially a frontend for Docker Compose. In this case, you can simply replicate the example docker-compose file available at [here](https://gamevau.lt/docs/server-docs/setup/docker-compose#step-1-creating-a-docker-compose-file)

Though I haven't personally utilized Synology Container Manager, I can attempt to provide a brief written guide based on my understanding, primarily referencing [this resource](https://drfrankenstein.co.uk/jellyseerr-in-container-manager-on-a-synology-nas/). Please bear with me if there are any discrepancies:

1. Begin by establishing folders for the containers to utilize. Navigate to File Station and create the following directories:

   - /docker/projects/gamevault-compose
   - /docker/gamevault
   - /docker/gamevault/files
   - /docker/gamevault/images
   - /docker/gamevault/database

2. Next, set up a 'Project' in Container Manager. Access Container Manager, click on 'Project,' and then click 'Create' on the right-hand side. Fill in the following details:

   - Project Name: gamevault
   - Path: /docker/projects/gamevault-compose
   - Source: Select 'Create docker-compose.yml'

3. Copy and paste the following code into the editor:

```yml
version: "3.8"
services:
  gamevault-backend:
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USERNAME: gamevault
      DB_PASSWORD: YOURDATABASEPASSWORD
      # Uncomment and insert your RAWG API Key here if you have one (http://rawg.io/login?forward=developer)
      # RAWG_API_KEY: YOURAPIKEYHERE
    volumes:
      - /volume1/docker/gamevault/files:/files
      - /volume1/docker/gamevault/images:/images
    ports:
      - 8080:8080/tcp #Change the left one if you want
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: YOURDATABASEPASSWORD
      POSTGRES_DB: gamevault
    volumes:
      - /volume1/docker/gamevault/database:/var/lib/postgresql/data
```

These settings should be sufficient to get the application up and running.

4. You should now be able to access the web interface via your NAS's IP address followed by port 8080.

5. If you wish to make the application accessible outside your LAN, you'll need to configure reverse proxy settings and possibly adjust firewall rules. Refer to guides similar to [https://drfrankenstein.co.uk/jellyseerr-in-container-manager-on-a-synology-nas/](https://drfrankenstein.co.uk/jellyseerr-in-container-manager-on-a-synology-nas/) for detailed instructions.

In general, you can often apply these guides to most Docker services, as the core concepts remain consistent (i.e., utilizing a compose file). It's advisable to read through the referenced guide as well, as it provides clearer explanations.

If this guide works for you, tell me so i can add it to our documentation :)
