### ISSUE TITLE
not respecting GAMES_INDEX_INTERVAL_IN_MINUTES=0 

### ISSUE THREAD

**Issue by wieluk** [Phalcode/gamevault-backend#286]
Hey, I set GAMES_INDEX_INTERVAL_IN_MINUTES=0 but I am still seeing a hourly disk spin up:

May 05 19:00:00 OPEN => /mnt/disk2/programs/games/Hades (V1.35966) (2020).7z
May 05 20:00:00 OPEN => /mnt/disk2/programs/games/Hades (V1.35966) (2020).7z
May 05 21:00:00 OPEN => /mnt/disk2/programs/games/Hades (V1.35966) (2020).7z

Do you know why this hapenning? Or what I can do to fix it?

**Comment by Alfagun74** [comment]
can you send me a log of your server from 1 minute after starting please?

**Comment by wieluk** [comment]
[gamevault-backend-2024-05-05.log](https://github.com/Phalcode/gamevault-backend/files/15214489/gamevault-backend-2024-05-05.log)

**Comment by Alfagun74** [comment]
Thanks. Well it seems your configuration is not being applied. 

The Log says:
```json
"INDEX_INTERVAL_IN_MINUTES":60
```

Are you sure you don't have a typo in your configuration?

The correct configuration would be:

```ini
GAMES_INDEX_INTERVAL_IN_MINUTES=0
```

**Comment by Alfagun74** [comment]
Wait i see the problem i think. It's actually a dumb Javascript thing on my end.

```
INDEX_INTERVAL_IN_MINUTES: Number(process.env.GAMES_INDEX_INTERVAL_IN_MINUTES) || 60,
```

gets evaluated as

```
INDEX_INTERVAL_IN_MINUTES: 0 || 60,
```

which in Javascript results in *60*.

gotta love this language.

Will fix it in the next update. Until then just use GAMES_INDEX_INTERVAL_IN_MINUTES=9999999999 or something lol.

**Comment by wieluk** [comment]
this is my compose:

```
services:
  gamevault-backend:
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/programs/games:/files
      - ./images:/images
      - ./logs:/logs
    environment:
      DB_HOST: db
      DB_USERNAME: name
      DB_PASSWORD: pass
      SERVER_LOG_FILES_ENABLED: true
      SERVER_ADMIN_USERNAME: user
      PUID: 1000
      PGID: 100
      SERVER_ACCOUNT_ACTIVATION_DISABLED: false
      GAMES_INDEX_INTERVAL_IN_MINUTES: 0
      RAWG_API_KEY: key
      GAMES_SEARCH_RECURSIVE: false
    ports:
      - 8283:8080/tcp
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: name
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gamevault
  ```
      
This should work right?
